@baseUrl = http://localhost:3333/api/v1

### User 
# @name create_user
POST {{baseUrl}}/users
Content-Type: application/json

{
  "username": "breno5g",
  "password": "@SenhaTop123"
}

### User Login
# @name login
GET {{baseUrl}}/users/login
Content-Type: application/json

{
  "username": "breno5g",
  "password": "@SenhaTop123"
}

# =-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-= #

### Create Category
# @name create_category
POST {{baseUrl}}/categories
Content-Type: application/json
Authorization: Bearer {{login.response.body.token}}

{
  "name": "Bebidas"
}

### Get Categories
# @name get_categories
GET {{baseUrl}}/categories
Content-Type: application/json
Authorization: Bearer {{login.response.body.token}}

# =-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-= #

### Create Transaction
# @name create_transaction
POST {{baseUrl}}/transactions
Content-Type: application/json
Authorization: Bearer {{login.response.body.token}}

{
  "category_id": "619d22f7-f998-4a15-b81e-71c4f4123691",
  "description": "Coquinha geladinha 2",
  "amount": 450,
  "type": "expense",
  "date": "2025-07-07"
}


### Get Transactions
# @name get_transactions
GET {{baseUrl}}/transactions
Content-Type: application/json
Authorization: Bearer {{login.response.body.token}}
