@baseUrl = http://localhost:3333/api/v1

### User 
# @name create_user
POST {{baseUrl}}/users
Content-Type: application/json

{
  "username": "breno5g",
  "password": "@SenhaTop123"
}

### User Login
# @name login
GET {{baseUrl}}/users/login
Content-Type: application/json

{
  "username": "breno5g",
  "password": "@SenhaTop123"
}

# =-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-= #

### Create Category
# @name create_category
POST {{baseUrl}}/categories
Content-Type: application/json
Authorization: Bearer {{login.response.body.token}}

{
  "name": "Cumida",
  "user_id": "1a8f7a16-1eee-4fe6-9414-359416b54dbb"
}

### Get Categories
# @name get_categories
GET {{baseUrl}}/categories
Content-Type: application/json
Authorization: Bearer {{login.response.body.token}}
