@baseUrl = http://localhost:3333/api/v1

### User 
# @name create_user
POST {{baseUrl}}/users
Content-Type: application/json

{
  "username": "breno5g",
  "password": "@SenhaTop123"
}

### User Login
# @name login
GET {{baseUrl}}/users/login
Content-Type: application/json

{
  "username": "breno5g",
  "password": "@SenhaTop123"
}

# =-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-= #

### Create Category
# @name create_category
POST {{baseUrl}}/categories
Content-Type: application/json
Authorization: Bearer {{login.response.body.token}}

{
  "name": "Pagamento"
}

### Get Categories
# @name get_categories
GET {{baseUrl}}/categories
Content-Type: application/json
Authorization: Bearer {{login.response.body.token}}

# =-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-= #

### Create Transaction
# @name create_transaction
POST {{baseUrl}}/transactions
Content-Type: application/json
Authorization: Bearer {{login.response.body.token}}

{
  "category_id": "ae2d6229-49a0-428f-bbb6-e676129c3359",
  "description": "Pagamento Sizebay",
  "amount": 536500,
  "type": "income",
  "date": "2025-06-30"
}


### Get Transactions
# @name get_transactions
GET {{baseUrl}}/transactions
Content-Type: application/json
Authorization: Bearer {{login.response.body.token}}
